### ISSUE TITLE
run "when app is open"

### ISSUE THREAD

**Issue by Eddy2909** [Zillode/syncthing-silk#33]
the app closes, when the device going to "sleep" (screen locked) altough using the setting "when app is open"..
whatever its called, when it disables the screen.. :/

I thought the app should run in background too? otherwise there is no option to let it run while the devices is locked..

**Comment by Zillode** [comment]
Could you try switching to `run when open` and then back to `always`? There was a bug in the visualisation of the current option.

**Comment by Eddy2909** [comment]
yes.. I do.. 
I'm using "always" while its running.. to shutdown syncthing&the app I'm using "when open"..
but whats the difference to shutdown the local syncthing intance?

Am 28. August 2015 08:41:31 MESZ, schrieb Zillode <notifications@github.com>:

**Comment by Zillode** [comment]
It should start the local instance if you select `when open`

**Comment by jonada** [comment]
Here is a suggestion for new option names in order to clarify what they really do:

"When app is open" --> "When app is in use (active)"
Simply saying "active" would be confusing since it does not sync when the app has been activated and the phone goes to sleep (it is clear for a developer, not for an end user).

"Always run" --> "In background (always sync)"
This is the least confusing option.

"Between scheduled times" --> "In background within schedule (no autostart)"
This is the most confusing option. If you manually start the app it stays on in the background until the end time is reached, then it gracefully closes down. However, it does not automatically start when the start time is reached (which would be the expected option). You have to manually start the app to make it run again (or start it through another app, such as Llama). When manually started, the app gracefully shutsdown when you leave the app and the current time is not within the schedule. Actually, this is really great when used with Llama or similar app.

Thanks for a great app!

**Comment by Zillode** [comment]
https://github.com/OpenSilk/SyncthingAndroid/commit/1dd6e6ab31ce86ee56f512b4f42e86a3b820f69a
