### ISSUE TITLE
Add Silk to F-Droid

### ISSUE THREAD

**Issue by rodneyrod** [Zillode/syncthing-silk#44]

**Comment by Zillode** [comment]
It is not that easy because we cannot rely on compiled code, but a PR is welcome.
Since Go1.5 is self-compiled, this means we have to download the Go1.4 source, compile it, download the Go1.5 source and bootstrap it using the Go1.4 we just compiled. This is a lot of compilation overhead and we need to get the script right to support cross-compilation (arm and x86 for android).

**Comment by Zillode** [comment]
Drew started an fdroid repo to host Syncthing-Silk at https://ssl.opensilk.org/fdroid/repo
Simply add it to the repositories in the F-Droid app and install Syncthing-Silk;)
